release script looks good

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,9 +1,10 @@
 #!/bin/bash
 
 module=$(basename $(pwd))
+script_dir=$(cd "$(dirname "$0")"; pwd -P)
 
 test -f .release-skip && { echo "$module: Skipping"; exit 0; }
-test -f pom.xml || { echo "$module: Should be maven project. Skipped."; exit 0; }
+test -f pom.xml -o -f version || { echo "$module: Should be Maven or Generic project. Skipped."; exit 0; }
 test -e .git || { echo "$module: Should be GIT root. Skipped."; exit 0; }
 git diff-index --quiet HEAD || { echo "$module: Uncommited changes. Terminate"; exit 1; }
 
@@ -14,32 +15,32 @@ rel_tag=v$rel_ver
 
 cur_branch=$(git rev-parse --abbrev-ref HEAD)
 
+test -f version && . $script_dir/generic_api || . $script_dir/maven_api
+
+echo "$module: Release via $release_api_name"
+
 echo "$module: BEGIN" && \
 	\
 	git checkout -b $rel_branch && \
-	sed -e "s/\.version>CURRENT-SNAPSHOT<\//\.version>$rel_ver<\//g" -i "" pom.xml && \
-	git diff && \
-	git add pom.xml && \
-	{ git diff-index --quiet HEAD || git commit -m "[release $rel_ver] Dependencies pre-release updated"; } && \
 	\
-	mvn release:prepare -DdevelopmentVersion=CURRENT-SNAPSHOT -DreleaseVersion=$rel_ver -DupdateDependencies=false -Darguments="-Dsign=true" --batch-mode && \
-	mvn release:perform -DskipTests -Darguments=-DskipTests && \
+# do release
+	before_release && \
+	do_release && \
+	after_release && \
 	\
-	sed -e "s/\.version>$rel_ver<\//\.version>CURRENT-SNAPSHOT<\//g" -i "" pom.xml && \
-	git diff && \
-	git add pom.xml && \
-	{ git diff-index --quiet HEAD || git commit -m "[release $rel_ver] Dependencies post-release updated"; } && \
-	\
+# merge release branch to current (master?)
 	git checkout $cur_branch && \
 	git merge --no-ff --no-edit $rel_branch && \
 	git push origin $cur_branch && \
-	git branch -d $rel_branch && \
 	\
-	git push --delete origin $rel_branch && \
-	\
+# tagging LATEST
 	git tag -f LATEST $rel_tag && \
 	git push -f origin LATEST && \
+	\
+# cleanup release branch
+	git branch -d $rel_branch && \
+	git push --delete origin $rel_branch && \
+	\
 	git checkout LATEST && \
 	\
 	echo "$module: DONE"
-
